spring.application.name=tienda-lem-lah-api

server.port=8000

spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data/data.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT (se usará en commit 2)
jwt.secret=dGllbmRhLWxlbS1sYWgtc2VjcmV0LWtleS1wYXJhLWp3dC0yNTZiaXRz
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000